Test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -33,11 +33,18 @@ jobs:
           liveChatUrl=$(echo "$json_data" | jq -r '.[0]["livechat-url"]')
           imageLogo=$(echo "$json_data" | jq -r '.[0]["image-logo"]')
           metaSource=$(echo "$json_data" | jq -r '.[0]["meta-source"]')
+          templateType=$(echo "$json_data" | jq -r '.[0].template')
 
           escape_sed() {
               echo "$1" | sed -e 's/[\/&]/\\&/g'
           }
 
+          # Check if templateType is not empty
+          if [ -z "$templateType" ]; then
+              echo "Template type is missing or invalid."
+              exit 1
+          fi
+          
           # Determine which template to use
           if [ "$templateType" -eq 1 ]; then
               templateFile="template.html"
